language: android
jdk:
  - oraclejdk8

android:
  
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-23

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-17
script:
  - ./gradlew build artifactoryPublish
